apiVersion: v1
kind: Secret
metadata:
 name: go-app-secrets
type: Opaque
data:
 USER: "YnNk"
 PASS: "YXJ0"
 SECRET: "QmVzdCBTZWNyZXQgRXZlciBpbiB0aGUgdW5pdmVyc2U="
 OWNER_UUID: "MmU1ZWQzZDItZjhlYS00YWVmLWFlYzAtZTQyNzJiYWE5YzBi"
